version: "3.9"

networks:
  laravel:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/etc/nginx/certs
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    #command: apk update && apk add openssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048    -subj "/C=GE/SN=Tbilisi/L=Tbilisi/O=org.local/OU=unit.local/CN=laravel.local" -addext "subjectAltName=email:admin@admin.ge subjectAltName=DNS:laravel.local"    -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: php
    tty: true
    volumes:
      - ./src:/var/www/html
    ports:
      - "9009:9000"
    networks:
      - laravel

  mysql:
    image: mysql:5.7.35
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4406:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      #- ./src/.env
      - .env
    environment:
      #!!! in case of pass change, `./data/mysql` must be removed!
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-mysql}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-mysql}
    depends_on:
      - mysql
    networks:
      - laravel